### ISSUE TITLE
你好，我这边测试输出的结果的格式不对，就是output.txt文件，而且准确率为0,请问是什么原因?

### ISSUE THREAD

**Issue by jieyang123** [Pydataman/daguan_information_extraction#1]

**Comment by Pydataman** [comment]
@jieyang123  测试文件输出格式不对？

**Comment by DengYangyong** [comment]
什么鬼代码，一堆问题，这是你跑过的代码吗？首先你说词向量是随机初始化的，那么参数设置那里应该是：action='store_false'，其次数据是iob格式的，那么在evaluator.py里要改。还有，测试结果怎么转换为官方要求的格式，你这里有代码吗？readme里面尽瞎写。

**Comment by jieyang123** [comment]
您好，我的运行记录是这样的，为什么dev_acc是0.000,是我哪里改错了代码吗？
DEV : B-b : dev_f1: 0.0516 dev_rec: 0.5769 dev_pre: 0.0270 dev_acc: 0.0000 | {'I-b': 1, 'O': 1583, 'B-c': 20, 'B-a': 2, 'I-c': 14}

(loss: 11.8324, epoch: 4, dev F1 = 0.0452, dev acc = 0.8771,), saving...
epoch: 4         in 100 take: 482.1453890800476 s
DEV : I-c : dev_f1: 0.1886 dev_rec: 0.5520 dev_pre: 0.1137 dev_acc: 0.0000 | {'O': 1569, 'I-b': 11, 'B-b': 6, 'B-c': 20, 'I-a': 7}

DEV : I-b : dev_f1: 0.0503 dev_rec: 0.4453 dev_pre: 0.0266 dev_acc: 0.0000 | {'I-c': 64, 'I-a': 9, 'B-a': 1, 'O': 1994, 'B-c': 8, 'B-b': 6}

DEV : B-c : dev_f1: 0.2238 dev_rec: 0.5610 dev_pre: 0.1398 dev_acc: 0.0000 | {'I-c': 6, 'I-b': 1, 'B-a': 2, 'O': 833, 'I-a': 2, 'B-b': 5}

DEV : B-a : dev_f1: 0.0281 dev_rec: 0.4444 dev_pre: 0.0145 dev_acc: 0.0000 | {'I-c': 2, 'I-b': 1, 'I-a': 18, 'O': 1044, 'B-c': 10, 'B-b': 12}

DEV : total : dev_f1: 0.0499 dev_rec: 0.2732 dev_pre: 0.0274 dev_acc: 0.8770 | 

DEV : O : dev_f1: 0.9357 dev_rec: 0.8810 dev_pre: 0.9976 dev_acc: 0.0000 | {'I-c': 48, 'I-b': 26, 'B-a': 7, 'I-a': 60, 'B-c': 42, 'B-b': 13}

DEV : I-a : dev_f1: 0.0735 dev_rec: 0.6340 dev_pre: 0.0390 dev_acc: 0.0000 | {'I-c': 30, 'I-b': 29, 'B-a': 7, 'O': 4061, 'B-c': 3, 'B-b': 8}

DEV : B-b : dev_f1: 0.0511 dev_rec: 0.4737 dev_pre: 0.0270 dev_acc: 0.0000 | {'I-c': 18, 'I-b': 3, 'B-a': 3, 'I-a': 1, 'O': 1570, 'B-c': 25}

**Comment by jieyang123** [comment]
@Pydataman

**Comment by Pydataman** [comment]
@DengYangyong 
针对你的问题，我一一给你解答，除了遗漏一个函数以外，本地跑通了
1、你没仔细看train.py代码么？不用改配置，python3 train.py --randn_embedding即可；
2、我上传遗漏了evaluator.py，和原本开源的代码一样，没改什么，BIO格式在label体现；
3、请看pre_data.py最后一个函数；
不看代码就跑，不出bug才怪
再者，不是拿到一份代码先熟悉一下？我readme写的很简洁，不要本着拿来就能用的原则。
请尊重别人，看不懂就别杠，ok？

**Comment by Pydataman** [comment]
@jieyang123 不好意思，才看到
你把遗漏的evaluator.py加进去了么？这个和开源的一样，我没改什么
看下train.py里面的参数
--eva_matrix  choices=['a', 'fa'], default='fa', help='use f1 and accuracy or accuracy alone'

**Comment by Pydataman** [comment]
@jieyang123 你可以直接给我发邮件，在主页就有，我每天都会看邮件。也可以一起组队啊，一起学习

**Comment by jieyang123** [comment]
你好，回复晚了不好意思，得到博主的回复非常感谢，我是自己一个人在打比赛，那我可以加入你的队伍嘛，和博主一起打比赛，我这边这一两周也在一直跑比赛代码，谢谢博主哇😃😃！



---原始邮件---
发件人: "eagle"<notifications@github.com>
发送时间: 2019年8月4日(星期日) 晚上7:30
收件人: "Pydataman/daguan_information_extraction"<daguan_information_extraction@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"bear"<1661075801@qq.com>;
主题: Re: [Pydataman/daguan_information_extraction] 你好，我这边测试输出的结果的格式不对，就是output.txt文件，而且准确率为0,请问是什么原因? (#1)



@jieyang123 你可以直接给我发邮件，在主页就有，我每天都会看邮件。也可以一起组队啊，一起学习

**Comment by Pydataman** [comment]
@jieyang123 你把你联系方式邮件发给我  我主页有邮件地址
